title: Ziqun Li # your name (or website title) here
logo: "/images/photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of Urban Spatial Analytics 
  <br><br>
  University of Pennsylvania
  <br><br>
  <a href="https://www.linkedin.com/in/ziqun-li-73033417b/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
