title: Ziqun Li # your name (or website title) here
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description:  > # your text below (remove <br> elements if you don't need line breaks)
  It is such a beautiful thing to be both a data geek and design aficionado.     
  <br><br>      
  My diverse background in design, data analysis, programming and GIS keeps me curious about everything, and my unique passion for creating dynamic solutions to complex problems allows me to thrive anywhere.    
  <br><br> 

theme: jekyll-theme-minimal
google_analytics: UA-156447358-1 # your Google Analytics tracking ID here
